### ISSUE TITLE
Database connection lost

### ISSUE THREAD

**Issue by mgns** [pmeinhardt/tlr#2]
After less than 15 minutes of inactivity:
OperationalError: (2006, "MySQL server has gone away (error(32, 'Broken pipe'))")

**Comment by pmeinhardt** [comment]
Issue https://github.com/coleifer/peewee/issues/489 looks like it might be an explanation. We should probably pass the `stale_timeout=...` argument when creating the pooled database connection in [app.py](https://github.com/pmeinhardt/tlr/blob/98c1070d2f98f02954fa659bd11d6f224e626786/app.py#L23).

It's strange though it goes away after such a short time. The MariaDB wait timeout is 8h (checked with the MariaDB docker image).

Maybe you can do these 2 things:
1. Insert `stale_timeout=300` in the database initialization
2. Make sure to rebuild the container after the changes
   - e.g. use a different image tag for building `docker build -t staletime .`
   - …and use this tag in the commands to run the container

Line 23 in app.py should look like this then:

``` ruby
self.database = Database(**dbconf, stale_timeout=300)
```

Can you try this out on the server and check whether the connection still goes away?

Thanks. Cheers,
Paul

**Comment by pmeinhardt** [comment]
Fixed in https://github.com/pmeinhardt/tlr/commit/79ab69463b1f784710650b9c37c61991b05e1e76
